kind: pipeline
type: docker
name: Deploiement

trigger:
  event:
    - push

steps:
  - name: docker-build-and-push
    image: plugins/docker
    settings:
       dockerfile: Docker/Dockerfile
       context: .
       registry: hub.codefirst.iut.uca.fr
       mirror: https://proxy.iut.uca.fr:8443
       repo: hub.codefirst.iut.uca.fr/thomas.muzard/portfolio_3a
       username:
         from_secret: SECRET_REGISTRY_USERNAME
       password:
         from_secret: SECRET_REGISTRY_PASSWORD

  - name: deploy-container
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: hub.codefirst.iut.uca.fr/thomas.muzard/portfolio_3a:latest
        CONTAINERNAME: portfolio_muzard_3a
        COMMAND: create
        OVERWRITE: true
